// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_proto.proto

package server_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Remember             bool     `protobuf:"varint,3,opt,name=remember" json:"remember,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{0}
}
func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (dst *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(dst, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthRequest) GetRemember() bool {
	if m != nil {
		return m.Remember
	}
	return false
}

type AuthCredentials struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthCredentials) Reset()         { *m = AuthCredentials{} }
func (m *AuthCredentials) String() string { return proto.CompactTextString(m) }
func (*AuthCredentials) ProtoMessage()    {}
func (*AuthCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{1}
}
func (m *AuthCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthCredentials.Unmarshal(m, b)
}
func (m *AuthCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthCredentials.Marshal(b, m, deterministic)
}
func (dst *AuthCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthCredentials.Merge(dst, src)
}
func (m *AuthCredentials) XXX_Size() int {
	return xxx_messageInfo_AuthCredentials.Size(m)
}
func (m *AuthCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_AuthCredentials proto.InternalMessageInfo

func (m *AuthCredentials) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthCredentials) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type AuthResponse struct {
	// Types that are valid to be assigned to Response:
	//	*AuthResponse_Available
	//	*AuthResponse_Payload
	Response             isAuthResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{2}
}
func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (dst *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(dst, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

type isAuthResponse_Response interface {
	isAuthResponse_Response()
}

type AuthResponse_Available struct {
	Available bool `protobuf:"varint,1,opt,name=available,oneof"`
}
type AuthResponse_Payload struct {
	Payload *AuthCredentials `protobuf:"bytes,2,opt,name=payload,oneof"`
}

func (*AuthResponse_Available) isAuthResponse_Response() {}
func (*AuthResponse_Payload) isAuthResponse_Response()   {}

func (m *AuthResponse) GetResponse() isAuthResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *AuthResponse) GetAvailable() bool {
	if x, ok := m.GetResponse().(*AuthResponse_Available); ok {
		return x.Available
	}
	return false
}

func (m *AuthResponse) GetPayload() *AuthCredentials {
	if x, ok := m.GetResponse().(*AuthResponse_Payload); ok {
		return x.Payload
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AuthResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AuthResponse_OneofMarshaler, _AuthResponse_OneofUnmarshaler, _AuthResponse_OneofSizer, []interface{}{
		(*AuthResponse_Available)(nil),
		(*AuthResponse_Payload)(nil),
	}
}

func _AuthResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AuthResponse)
	// response
	switch x := m.Response.(type) {
	case *AuthResponse_Available:
		t := uint64(0)
		if x.Available {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *AuthResponse_Payload:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Payload); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AuthResponse.Response has unexpected type %T", x)
	}
	return nil
}

func _AuthResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AuthResponse)
	switch tag {
	case 1: // response.available
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Response = &AuthResponse_Available{x != 0}
		return true, err
	case 2: // response.payload
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AuthCredentials)
		err := b.DecodeMessage(msg)
		m.Response = &AuthResponse_Payload{msg}
		return true, err
	default:
		return false, nil
	}
}

func _AuthResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AuthResponse)
	// response
	switch x := m.Response.(type) {
	case *AuthResponse_Available:
		n += 1 // tag and wire
		n += 1
	case *AuthResponse_Payload:
		s := proto.Size(x.Payload)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Describes a tile on the board
type TileCoord struct {
	Horizontal           uint32   `protobuf:"varint,1,opt,name=horizontal" json:"horizontal,omitempty"`
	Vertical             uint32   `protobuf:"varint,2,opt,name=vertical" json:"vertical,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileCoord) Reset()         { *m = TileCoord{} }
func (m *TileCoord) String() string { return proto.CompactTextString(m) }
func (*TileCoord) ProtoMessage()    {}
func (*TileCoord) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{3}
}
func (m *TileCoord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileCoord.Unmarshal(m, b)
}
func (m *TileCoord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileCoord.Marshal(b, m, deterministic)
}
func (dst *TileCoord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileCoord.Merge(dst, src)
}
func (m *TileCoord) XXX_Size() int {
	return xxx_messageInfo_TileCoord.Size(m)
}
func (m *TileCoord) XXX_DiscardUnknown() {
	xxx_messageInfo_TileCoord.DiscardUnknown(m)
}

var xxx_messageInfo_TileCoord proto.InternalMessageInfo

func (m *TileCoord) GetHorizontal() uint32 {
	if m != nil {
		return m.Horizontal
	}
	return 0
}

func (m *TileCoord) GetVertical() uint32 {
	if m != nil {
		return m.Vertical
	}
	return 0
}

// Describes a node on the board
type NodeCoord struct {
	Horizontal           uint32   `protobuf:"varint,1,opt,name=horizontal" json:"horizontal,omitempty"`
	Vertical             uint32   `protobuf:"varint,2,opt,name=vertical" json:"vertical,omitempty"`
	Upper                bool     `protobuf:"varint,3,opt,name=upper" json:"upper,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeCoord) Reset()         { *m = NodeCoord{} }
func (m *NodeCoord) String() string { return proto.CompactTextString(m) }
func (*NodeCoord) ProtoMessage()    {}
func (*NodeCoord) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{4}
}
func (m *NodeCoord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeCoord.Unmarshal(m, b)
}
func (m *NodeCoord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeCoord.Marshal(b, m, deterministic)
}
func (dst *NodeCoord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeCoord.Merge(dst, src)
}
func (m *NodeCoord) XXX_Size() int {
	return xxx_messageInfo_NodeCoord.Size(m)
}
func (m *NodeCoord) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeCoord.DiscardUnknown(m)
}

var xxx_messageInfo_NodeCoord proto.InternalMessageInfo

func (m *NodeCoord) GetHorizontal() uint32 {
	if m != nil {
		return m.Horizontal
	}
	return 0
}

func (m *NodeCoord) GetVertical() uint32 {
	if m != nil {
		return m.Vertical
	}
	return 0
}

func (m *NodeCoord) GetUpper() bool {
	if m != nil {
		return m.Upper
	}
	return false
}

// Describes a player action
type GameAction struct {
	// Types that are valid to be assigned to Coordinate:
	//	*GameAction_TilePos
	//	*GameAction_NodePos
	Coordinate           isGameAction_Coordinate `protobuf_oneof:"coordinate"`
	Action               uint32                  `protobuf:"varint,3,opt,name=action" json:"action,omitempty"`
	Issuer               uint32                  `protobuf:"varint,4,opt,name=issuer" json:"issuer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GameAction) Reset()         { *m = GameAction{} }
func (m *GameAction) String() string { return proto.CompactTextString(m) }
func (*GameAction) ProtoMessage()    {}
func (*GameAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{5}
}
func (m *GameAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameAction.Unmarshal(m, b)
}
func (m *GameAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameAction.Marshal(b, m, deterministic)
}
func (dst *GameAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameAction.Merge(dst, src)
}
func (m *GameAction) XXX_Size() int {
	return xxx_messageInfo_GameAction.Size(m)
}
func (m *GameAction) XXX_DiscardUnknown() {
	xxx_messageInfo_GameAction.DiscardUnknown(m)
}

var xxx_messageInfo_GameAction proto.InternalMessageInfo

type isGameAction_Coordinate interface {
	isGameAction_Coordinate()
}

type GameAction_TilePos struct {
	TilePos *TileCoord `protobuf:"bytes,1,opt,name=tilePos,oneof"`
}
type GameAction_NodePos struct {
	NodePos *NodeCoord `protobuf:"bytes,2,opt,name=nodePos,oneof"`
}

func (*GameAction_TilePos) isGameAction_Coordinate() {}
func (*GameAction_NodePos) isGameAction_Coordinate() {}

func (m *GameAction) GetCoordinate() isGameAction_Coordinate {
	if m != nil {
		return m.Coordinate
	}
	return nil
}

func (m *GameAction) GetTilePos() *TileCoord {
	if x, ok := m.GetCoordinate().(*GameAction_TilePos); ok {
		return x.TilePos
	}
	return nil
}

func (m *GameAction) GetNodePos() *NodeCoord {
	if x, ok := m.GetCoordinate().(*GameAction_NodePos); ok {
		return x.NodePos
	}
	return nil
}

func (m *GameAction) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *GameAction) GetIssuer() uint32 {
	if m != nil {
		return m.Issuer
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GameAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GameAction_OneofMarshaler, _GameAction_OneofUnmarshaler, _GameAction_OneofSizer, []interface{}{
		(*GameAction_TilePos)(nil),
		(*GameAction_NodePos)(nil),
	}
}

func _GameAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GameAction)
	// coordinate
	switch x := m.Coordinate.(type) {
	case *GameAction_TilePos:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TilePos); err != nil {
			return err
		}
	case *GameAction_NodePos:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NodePos); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GameAction.Coordinate has unexpected type %T", x)
	}
	return nil
}

func _GameAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GameAction)
	switch tag {
	case 1: // coordinate.tilePos
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TileCoord)
		err := b.DecodeMessage(msg)
		m.Coordinate = &GameAction_TilePos{msg}
		return true, err
	case 2: // coordinate.nodePos
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NodeCoord)
		err := b.DecodeMessage(msg)
		m.Coordinate = &GameAction_NodePos{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GameAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GameAction)
	// coordinate
	switch x := m.Coordinate.(type) {
	case *GameAction_TilePos:
		s := proto.Size(x.TilePos)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameAction_NodePos:
		s := proto.Size(x.NodePos)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Sent when a player connects / disconnects
type ConnectionMessage struct {
	Connection           bool        `protobuf:"varint,1,opt,name=connection" json:"connection,omitempty"`
	Player               *PlayerInfo `protobuf:"bytes,2,opt,name=player" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConnectionMessage) Reset()         { *m = ConnectionMessage{} }
func (m *ConnectionMessage) String() string { return proto.CompactTextString(m) }
func (*ConnectionMessage) ProtoMessage()    {}
func (*ConnectionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{6}
}
func (m *ConnectionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionMessage.Unmarshal(m, b)
}
func (m *ConnectionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionMessage.Marshal(b, m, deterministic)
}
func (dst *ConnectionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionMessage.Merge(dst, src)
}
func (m *ConnectionMessage) XXX_Size() int {
	return xxx_messageInfo_ConnectionMessage.Size(m)
}
func (m *ConnectionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionMessage proto.InternalMessageInfo

func (m *ConnectionMessage) GetConnection() bool {
	if m != nil {
		return m.Connection
	}
	return false
}

func (m *ConnectionMessage) GetPlayer() *PlayerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

type BoardBytes struct {
	State                []byte   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Issuer               uint32   `protobuf:"varint,2,opt,name=issuer" json:"issuer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoardBytes) Reset()         { *m = BoardBytes{} }
func (m *BoardBytes) String() string { return proto.CompactTextString(m) }
func (*BoardBytes) ProtoMessage()    {}
func (*BoardBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{7}
}
func (m *BoardBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardBytes.Unmarshal(m, b)
}
func (m *BoardBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardBytes.Marshal(b, m, deterministic)
}
func (dst *BoardBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardBytes.Merge(dst, src)
}
func (m *BoardBytes) XXX_Size() int {
	return xxx_messageInfo_BoardBytes.Size(m)
}
func (m *BoardBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardBytes.DiscardUnknown(m)
}

var xxx_messageInfo_BoardBytes proto.InternalMessageInfo

func (m *BoardBytes) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *BoardBytes) GetIssuer() uint32 {
	if m != nil {
		return m.Issuer
	}
	return 0
}

// In-game message, can be either connection or action
type GameMessage struct {
	// Types that are valid to be assigned to Payload:
	//	*GameMessage_Action
	//	*GameMessage_ConnectionInfo
	//	*GameMessage_RoomInfo
	//	*GameMessage_BoardState
	Payload              isGameMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GameMessage) Reset()         { *m = GameMessage{} }
func (m *GameMessage) String() string { return proto.CompactTextString(m) }
func (*GameMessage) ProtoMessage()    {}
func (*GameMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{8}
}
func (m *GameMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameMessage.Unmarshal(m, b)
}
func (m *GameMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameMessage.Marshal(b, m, deterministic)
}
func (dst *GameMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameMessage.Merge(dst, src)
}
func (m *GameMessage) XXX_Size() int {
	return xxx_messageInfo_GameMessage.Size(m)
}
func (m *GameMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GameMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GameMessage proto.InternalMessageInfo

type isGameMessage_Payload interface {
	isGameMessage_Payload()
}

type GameMessage_Action struct {
	Action *GameAction `protobuf:"bytes,1,opt,name=action,oneof"`
}
type GameMessage_ConnectionInfo struct {
	ConnectionInfo *ConnectionMessage `protobuf:"bytes,2,opt,name=connectionInfo,oneof"`
}
type GameMessage_RoomInfo struct {
	RoomInfo *RoomDetail `protobuf:"bytes,3,opt,name=roomInfo,oneof"`
}
type GameMessage_BoardState struct {
	BoardState *BoardBytes `protobuf:"bytes,4,opt,name=boardState,oneof"`
}

func (*GameMessage_Action) isGameMessage_Payload()         {}
func (*GameMessage_ConnectionInfo) isGameMessage_Payload() {}
func (*GameMessage_RoomInfo) isGameMessage_Payload()       {}
func (*GameMessage_BoardState) isGameMessage_Payload()     {}

func (m *GameMessage) GetPayload() isGameMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GameMessage) GetAction() *GameAction {
	if x, ok := m.GetPayload().(*GameMessage_Action); ok {
		return x.Action
	}
	return nil
}

func (m *GameMessage) GetConnectionInfo() *ConnectionMessage {
	if x, ok := m.GetPayload().(*GameMessage_ConnectionInfo); ok {
		return x.ConnectionInfo
	}
	return nil
}

func (m *GameMessage) GetRoomInfo() *RoomDetail {
	if x, ok := m.GetPayload().(*GameMessage_RoomInfo); ok {
		return x.RoomInfo
	}
	return nil
}

func (m *GameMessage) GetBoardState() *BoardBytes {
	if x, ok := m.GetPayload().(*GameMessage_BoardState); ok {
		return x.BoardState
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GameMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GameMessage_OneofMarshaler, _GameMessage_OneofUnmarshaler, _GameMessage_OneofSizer, []interface{}{
		(*GameMessage_Action)(nil),
		(*GameMessage_ConnectionInfo)(nil),
		(*GameMessage_RoomInfo)(nil),
		(*GameMessage_BoardState)(nil),
	}
}

func _GameMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GameMessage)
	// payload
	switch x := m.Payload.(type) {
	case *GameMessage_Action:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Action); err != nil {
			return err
		}
	case *GameMessage_ConnectionInfo:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ConnectionInfo); err != nil {
			return err
		}
	case *GameMessage_RoomInfo:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RoomInfo); err != nil {
			return err
		}
	case *GameMessage_BoardState:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoardState); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GameMessage.Payload has unexpected type %T", x)
	}
	return nil
}

func _GameMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GameMessage)
	switch tag {
	case 1: // payload.action
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GameAction)
		err := b.DecodeMessage(msg)
		m.Payload = &GameMessage_Action{msg}
		return true, err
	case 2: // payload.connectionInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ConnectionMessage)
		err := b.DecodeMessage(msg)
		m.Payload = &GameMessage_ConnectionInfo{msg}
		return true, err
	case 3: // payload.roomInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RoomDetail)
		err := b.DecodeMessage(msg)
		m.Payload = &GameMessage_RoomInfo{msg}
		return true, err
	case 4: // payload.boardState
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoardBytes)
		err := b.DecodeMessage(msg)
		m.Payload = &GameMessage_BoardState{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GameMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GameMessage)
	// payload
	switch x := m.Payload.(type) {
	case *GameMessage_Action:
		s := proto.Size(x.Action)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_ConnectionInfo:
		s := proto.Size(x.ConnectionInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_RoomInfo:
		s := proto.Size(x.RoomInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_BoardState:
		s := proto.Size(x.BoardState)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Sent to cancel a request or for roomcheck
type RoomRequestMessage struct {
	Cancel               bool     `protobuf:"varint,1,opt,name=cancel" json:"cancel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomRequestMessage) Reset()         { *m = RoomRequestMessage{} }
func (m *RoomRequestMessage) String() string { return proto.CompactTextString(m) }
func (*RoomRequestMessage) ProtoMessage()    {}
func (*RoomRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{9}
}
func (m *RoomRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomRequestMessage.Unmarshal(m, b)
}
func (m *RoomRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomRequestMessage.Marshal(b, m, deterministic)
}
func (dst *RoomRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomRequestMessage.Merge(dst, src)
}
func (m *RoomRequestMessage) XXX_Size() int {
	return xxx_messageInfo_RoomRequestMessage.Size(m)
}
func (m *RoomRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RoomRequestMessage proto.InternalMessageInfo

func (m *RoomRequestMessage) GetCancel() bool {
	if m != nil {
		return m.Cancel
	}
	return false
}

// Answer to a room request, can be either false or the room info
type RoomResponse struct {
	// Types that are valid to be assigned to Response:
	//	*RoomResponse_Available
	//	*RoomResponse_Info
	Response             isRoomResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RoomResponse) Reset()         { *m = RoomResponse{} }
func (m *RoomResponse) String() string { return proto.CompactTextString(m) }
func (*RoomResponse) ProtoMessage()    {}
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{10}
}
func (m *RoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomResponse.Unmarshal(m, b)
}
func (m *RoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomResponse.Marshal(b, m, deterministic)
}
func (dst *RoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomResponse.Merge(dst, src)
}
func (m *RoomResponse) XXX_Size() int {
	return xxx_messageInfo_RoomResponse.Size(m)
}
func (m *RoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomResponse proto.InternalMessageInfo

type isRoomResponse_Response interface {
	isRoomResponse_Response()
}

type RoomResponse_Available struct {
	Available bool `protobuf:"varint,1,opt,name=available,oneof"`
}
type RoomResponse_Info struct {
	Info *RoomInfo `protobuf:"bytes,2,opt,name=info,oneof"`
}

func (*RoomResponse_Available) isRoomResponse_Response() {}
func (*RoomResponse_Info) isRoomResponse_Response()      {}

func (m *RoomResponse) GetResponse() isRoomResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *RoomResponse) GetAvailable() bool {
	if x, ok := m.GetResponse().(*RoomResponse_Available); ok {
		return x.Available
	}
	return false
}

func (m *RoomResponse) GetInfo() *RoomInfo {
	if x, ok := m.GetResponse().(*RoomResponse_Info); ok {
		return x.Info
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RoomResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RoomResponse_OneofMarshaler, _RoomResponse_OneofUnmarshaler, _RoomResponse_OneofSizer, []interface{}{
		(*RoomResponse_Available)(nil),
		(*RoomResponse_Info)(nil),
	}
}

func _RoomResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RoomResponse)
	// response
	switch x := m.Response.(type) {
	case *RoomResponse_Available:
		t := uint64(0)
		if x.Available {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *RoomResponse_Info:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Info); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RoomResponse.Response has unexpected type %T", x)
	}
	return nil
}

func _RoomResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RoomResponse)
	switch tag {
	case 1: // response.available
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Response = &RoomResponse_Available{x != 0}
		return true, err
	case 2: // response.info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RoomInfo)
		err := b.DecodeMessage(msg)
		m.Response = &RoomResponse_Info{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RoomResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RoomResponse)
	// response
	switch x := m.Response.(type) {
	case *RoomResponse_Available:
		n += 1 // tag and wire
		n += 1
	case *RoomResponse_Info:
		s := proto.Size(x.Info)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Send information about the constitution of the room
type RoomDetail struct {
	RoomSize             uint32        `protobuf:"varint,1,opt,name=roomSize" json:"roomSize,omitempty"`
	Player               []*PlayerInfo `protobuf:"bytes,2,rep,name=player" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoomDetail) Reset()         { *m = RoomDetail{} }
func (m *RoomDetail) String() string { return proto.CompactTextString(m) }
func (*RoomDetail) ProtoMessage()    {}
func (*RoomDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{11}
}
func (m *RoomDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomDetail.Unmarshal(m, b)
}
func (m *RoomDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomDetail.Marshal(b, m, deterministic)
}
func (dst *RoomDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomDetail.Merge(dst, src)
}
func (m *RoomDetail) XXX_Size() int {
	return xxx_messageInfo_RoomDetail.Size(m)
}
func (m *RoomDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomDetail.DiscardUnknown(m)
}

var xxx_messageInfo_RoomDetail proto.InternalMessageInfo

func (m *RoomDetail) GetRoomSize() uint32 {
	if m != nil {
		return m.RoomSize
	}
	return 0
}

func (m *RoomDetail) GetPlayer() []*PlayerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

type PlayerInfo struct {
	PlayerNum            uint32   `protobuf:"varint,1,opt,name=playerNum" json:"playerNum,omitempty"`
	PlayerID             string   `protobuf:"bytes,2,opt,name=playerID" json:"playerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{12}
}
func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (dst *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(dst, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetPlayerNum() uint32 {
	if m != nil {
		return m.PlayerNum
	}
	return 0
}

func (m *PlayerInfo) GetPlayerID() string {
	if m != nil {
		return m.PlayerID
	}
	return ""
}

// Answer to a room request with corresponding ID
type RoomInfo struct {
	RoomID               uint32   `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
	PlayerNum            uint32   `protobuf:"varint,2,opt,name=playerNum" json:"playerNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_proto_1a323e1621505057, []int{13}
}
func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (dst *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(dst, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RoomInfo) GetPlayerNum() uint32 {
	if m != nil {
		return m.PlayerNum
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "AuthRequest")
	proto.RegisterType((*AuthCredentials)(nil), "AuthCredentials")
	proto.RegisterType((*AuthResponse)(nil), "AuthResponse")
	proto.RegisterType((*TileCoord)(nil), "TileCoord")
	proto.RegisterType((*NodeCoord)(nil), "NodeCoord")
	proto.RegisterType((*GameAction)(nil), "GameAction")
	proto.RegisterType((*ConnectionMessage)(nil), "ConnectionMessage")
	proto.RegisterType((*BoardBytes)(nil), "BoardBytes")
	proto.RegisterType((*GameMessage)(nil), "GameMessage")
	proto.RegisterType((*RoomRequestMessage)(nil), "RoomRequestMessage")
	proto.RegisterType((*RoomResponse)(nil), "RoomResponse")
	proto.RegisterType((*RoomDetail)(nil), "RoomDetail")
	proto.RegisterType((*PlayerInfo)(nil), "PlayerInfo")
	proto.RegisterType((*RoomInfo)(nil), "RoomInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Game service

type GameClient interface {
	GameStream(ctx context.Context, opts ...grpc.CallOption) (Game_GameStreamClient, error)
	RoomRequest(ctx context.Context, opts ...grpc.CallOption) (Game_RoomRequestClient, error)
	RoomCheck(ctx context.Context, in *RoomRequestMessage, opts ...grpc.CallOption) (*RoomResponse, error)
}

type gameClient struct {
	cc *grpc.ClientConn
}

func NewGameClient(cc *grpc.ClientConn) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) GameStream(ctx context.Context, opts ...grpc.CallOption) (Game_GameStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Game_serviceDesc.Streams[0], c.cc, "/Game/GameStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameGameStreamClient{stream}
	return x, nil
}

type Game_GameStreamClient interface {
	Send(*GameMessage) error
	Recv() (*GameMessage, error)
	grpc.ClientStream
}

type gameGameStreamClient struct {
	grpc.ClientStream
}

func (x *gameGameStreamClient) Send(m *GameMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameGameStreamClient) Recv() (*GameMessage, error) {
	m := new(GameMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameClient) RoomRequest(ctx context.Context, opts ...grpc.CallOption) (Game_RoomRequestClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Game_serviceDesc.Streams[1], c.cc, "/Game/RoomRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameRoomRequestClient{stream}
	return x, nil
}

type Game_RoomRequestClient interface {
	Send(*RoomRequestMessage) error
	Recv() (*RoomResponse, error)
	grpc.ClientStream
}

type gameRoomRequestClient struct {
	grpc.ClientStream
}

func (x *gameRoomRequestClient) Send(m *RoomRequestMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameRoomRequestClient) Recv() (*RoomResponse, error) {
	m := new(RoomResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameClient) RoomCheck(ctx context.Context, in *RoomRequestMessage, opts ...grpc.CallOption) (*RoomResponse, error) {
	out := new(RoomResponse)
	err := grpc.Invoke(ctx, "/Game/RoomCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Game service

type GameServer interface {
	GameStream(Game_GameStreamServer) error
	RoomRequest(Game_RoomRequestServer) error
	RoomCheck(context.Context, *RoomRequestMessage) (*RoomResponse, error)
}

func RegisterGameServer(s *grpc.Server, srv GameServer) {
	s.RegisterService(&_Game_serviceDesc, srv)
}

func _Game_GameStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServer).GameStream(&gameGameStreamServer{stream})
}

type Game_GameStreamServer interface {
	Send(*GameMessage) error
	Recv() (*GameMessage, error)
	grpc.ServerStream
}

type gameGameStreamServer struct {
	grpc.ServerStream
}

func (x *gameGameStreamServer) Send(m *GameMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameGameStreamServer) Recv() (*GameMessage, error) {
	m := new(GameMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Game_RoomRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServer).RoomRequest(&gameRoomRequestServer{stream})
}

type Game_RoomRequestServer interface {
	Send(*RoomResponse) error
	Recv() (*RoomRequestMessage, error)
	grpc.ServerStream
}

type gameRoomRequestServer struct {
	grpc.ServerStream
}

func (x *gameRoomRequestServer) Send(m *RoomResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameRoomRequestServer) Recv() (*RoomRequestMessage, error) {
	m := new(RoomRequestMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Game_RoomCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).RoomCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Game/RoomCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).RoomCheck(ctx, req.(*RoomRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Game_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RoomCheck",
			Handler:    _Game_RoomCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GameStream",
			Handler:       _Game_GameStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RoomRequest",
			Handler:       _Game_RoomRequest_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server_proto.proto",
}

// Client API for Auth service

type AuthClient interface {
	Authentication(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Authentication(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/Auth/Authentication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Authentication(context.Context, *AuthRequest) (*AuthResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Authentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Authentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Authentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Authentication(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authentication",
			Handler:    _Auth_Authentication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_proto.proto",
}

func init() { proto.RegisterFile("server_proto.proto", fileDescriptor_server_proto_1a323e1621505057) }

var fileDescriptor_server_proto_1a323e1621505057 = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xb6, 0xd3, 0x90, 0xc6, 0x93, 0xa4, 0xc0, 0x82, 0x4a, 0x14, 0xa1, 0x52, 0x19, 0x81, 0x8a,
	0x54, 0x0c, 0x84, 0x43, 0x25, 0xe0, 0x40, 0x93, 0x8a, 0xa6, 0x87, 0x56, 0xd5, 0x96, 0x03, 0x12,
	0x82, 0x6a, 0x63, 0x0f, 0xc4, 0xaa, 0xed, 0x35, 0xeb, 0x4d, 0x51, 0xfb, 0x28, 0x1c, 0x79, 0x29,
	0x5e, 0x07, 0xed, 0x4f, 0x6c, 0xa7, 0x15, 0x52, 0x25, 0x2e, 0x49, 0xbe, 0xd9, 0xd9, 0x99, 0xef,
	0x9b, 0x99, 0x9d, 0x00, 0x29, 0x50, 0x9c, 0xa3, 0x38, 0xcd, 0x05, 0x97, 0x3c, 0xd0, 0x9f, 0xfe,
	0x57, 0xe8, 0xec, 0xce, 0xe5, 0x8c, 0xe2, 0x8f, 0x39, 0x16, 0x92, 0x3c, 0x80, 0xd5, 0x79, 0x81,
	0xe2, 0x34, 0x8e, 0xfa, 0xee, 0xa6, 0xbb, 0xe5, 0xd1, 0x96, 0x82, 0x07, 0x11, 0x19, 0x40, 0x3b,
	0x67, 0x45, 0xf1, 0x93, 0x8b, 0xa8, 0xdf, 0xd0, 0x27, 0x25, 0x56, 0x67, 0x02, 0x53, 0x4c, 0xa7,
	0x28, 0xfa, 0x2b, 0x9b, 0xee, 0x56, 0x9b, 0x96, 0xd8, 0x7f, 0x0b, 0xb7, 0x55, 0xfc, 0xb1, 0xc0,
	0x08, 0x33, 0x19, 0xb3, 0xa4, 0x20, 0xf7, 0xe1, 0x96, 0xe4, 0x67, 0x98, 0xd9, 0x0c, 0x06, 0x10,
	0x02, 0xcd, 0x90, 0x47, 0x68, 0x83, 0xeb, 0xdf, 0xfe, 0x0c, 0xba, 0x86, 0x5c, 0x91, 0xf3, 0xac,
	0x40, 0xb2, 0x01, 0x1e, 0x3b, 0x67, 0x71, 0xc2, 0xa6, 0x09, 0xea, 0xdb, 0xed, 0x89, 0x43, 0x2b,
	0x13, 0xd9, 0x86, 0xd5, 0x9c, 0x5d, 0x24, 0x9c, 0x19, 0x8e, 0x9d, 0xe1, 0x9d, 0xe0, 0x4a, 0xf2,
	0x89, 0x43, 0x17, 0x2e, 0x23, 0x50, 0xb4, 0x4d, 0x64, 0x7f, 0x1f, 0xbc, 0x8f, 0x71, 0x82, 0x63,
	0xae, 0xf4, 0x6c, 0x00, 0xcc, 0xb8, 0x88, 0x2f, 0x79, 0x26, 0x59, 0xa2, 0xf3, 0xf4, 0x68, 0xcd,
	0xa2, 0xf4, 0x9e, 0xa3, 0x90, 0x71, 0xc8, 0x12, 0x9d, 0xa7, 0x47, 0x4b, 0xec, 0x7f, 0x01, 0xef,
	0x88, 0x47, 0xff, 0x1f, 0x48, 0x55, 0x69, 0x9e, 0xe7, 0x65, 0x45, 0x0d, 0xf0, 0x7f, 0xb9, 0x00,
	0xfb, 0x2c, 0xc5, 0xdd, 0x50, 0xc6, 0x3c, 0x23, 0x4f, 0x61, 0x55, 0xc6, 0x09, 0x1e, 0xf3, 0x42,
	0x47, 0xef, 0x0c, 0x21, 0x28, 0x65, 0x28, 0xa9, 0xf6, 0x50, 0xf9, 0x65, 0x3c, 0xd2, 0x7e, 0x0d,
	0xeb, 0x57, 0xb2, 0x54, 0x7e, 0xf6, 0x90, 0xac, 0x43, 0x8b, 0xe9, 0xc8, 0x3a, 0x6b, 0x8f, 0x5a,
	0xa4, 0xec, 0x71, 0x51, 0xcc, 0x51, 0xf4, 0x9b, 0xc6, 0x6e, 0xd0, 0xa8, 0x0b, 0x10, 0xaa, 0x18,
	0x71, 0xc6, 0x24, 0xfa, 0x9f, 0xe0, 0xee, 0x98, 0x67, 0x19, 0xea, 0x3b, 0x87, 0x58, 0x14, 0xec,
	0xbb, 0xea, 0x19, 0x84, 0xa5, 0xd1, 0x34, 0x8d, 0xd6, 0x2c, 0xe4, 0x31, 0xb4, 0xf2, 0x84, 0x5d,
	0xa0, 0xb0, 0xcc, 0x3a, 0xc1, 0xb1, 0x86, 0x07, 0xd9, 0x37, 0x4e, 0xed, 0x91, 0xff, 0x06, 0x60,
	0xc4, 0x99, 0x88, 0x46, 0x17, 0x12, 0xf5, 0x00, 0x15, 0x92, 0x49, 0x33, 0x02, 0x5d, 0x6a, 0x40,
	0x8d, 0x63, 0xa3, 0xce, 0xd1, 0xff, 0xe3, 0x42, 0x47, 0x95, 0x6c, 0x41, 0xe8, 0x49, 0xa9, 0xd1,
	0xb5, 0x09, 0xab, 0x82, 0x4e, 0x9c, 0x52, 0xf2, 0x3b, 0x58, 0xab, 0x58, 0x2a, 0x32, 0x96, 0x1f,
	0x09, 0xae, 0x69, 0x9c, 0x38, 0xf4, 0x8a, 0x2f, 0x79, 0x06, 0x6d, 0xc1, 0x79, 0xaa, 0xef, 0xad,
	0xd8, 0x34, 0x94, 0xf3, 0x74, 0x0f, 0x25, 0x8b, 0x93, 0x89, 0x43, 0xcb, 0x63, 0xf2, 0x1c, 0x60,
	0xaa, 0xb4, 0x9d, 0x68, 0x49, 0x4d, 0xeb, 0x5c, 0xc9, 0x9d, 0x38, 0xb4, 0xe6, 0x30, 0xf2, 0xca,
	0x19, 0xf7, 0xb7, 0x81, 0xa8, 0x98, 0xf6, 0xed, 0x2e, 0xf4, 0xad, 0x43, 0x2b, 0x64, 0x59, 0x88,
	0x89, 0x2d, 0xb6, 0x45, 0xfe, 0x67, 0xe8, 0x1a, 0xef, 0x1b, 0x3e, 0xa6, 0x47, 0xd0, 0x8c, 0x2b,
	0xd9, 0x9e, 0xa6, 0xaf, 0x08, 0x4f, 0x1c, 0xaa, 0x0f, 0x96, 0xde, 0xcf, 0x21, 0x40, 0x25, 0x4f,
	0x2f, 0x04, 0xce, 0xd3, 0x93, 0xf8, 0x12, 0xed, 0xd4, 0x97, 0x78, 0xa9, 0xdf, 0x2b, 0xff, 0xea,
	0xf7, 0x07, 0x80, 0xca, 0x4a, 0x1e, 0x82, 0x67, 0xec, 0x47, 0xf3, 0xd4, 0xc6, 0xab, 0x0c, 0x7a,
	0x33, 0x19, 0xdf, 0xbd, 0x72, 0x33, 0x59, 0xec, 0xbf, 0x87, 0xf6, 0x82, 0xb6, 0xaa, 0x8b, 0xae,
	0xf9, 0x9e, 0x0d, 0x61, 0xd1, 0x72, 0xf4, 0xc6, 0x95, 0xe8, 0xc3, 0xdf, 0x2e, 0x34, 0xd5, 0x7c,
	0x90, 0xc0, 0x3c, 0xbc, 0x13, 0x29, 0x90, 0xa5, 0xa4, 0x1b, 0xd4, 0x46, 0x6a, 0xb0, 0x84, 0x7c,
	0x67, 0xcb, 0x7d, 0xe9, 0x92, 0x1d, 0xe8, 0xd4, 0x9a, 0x43, 0xee, 0x05, 0xd7, 0x5b, 0x35, 0xe8,
	0x05, 0xf5, 0x8e, 0xd8, 0x8b, 0xaf, 0xc0, 0x53, 0xd6, 0xf1, 0x0c, 0xc3, 0xb3, 0x9b, 0x5d, 0x1b,
	0xee, 0x40, 0x53, 0xed, 0x39, 0xf2, 0x02, 0xd6, 0xd4, 0xb7, 0xda, 0x75, 0x21, 0xd3, 0x53, 0xdc,
	0x0d, 0x6a, 0xdb, 0x7d, 0xd0, 0x0b, 0xea, 0xeb, 0xd4, 0x77, 0xa6, 0x2d, 0xfd, 0x27, 0xf0, 0xfa,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x32, 0x16, 0x39, 0x1a, 0x06, 0x00, 0x00,
}
